export APPLICATION_NAME="sample-image"
export K8s_DEPLOYMENT_FILE="sample-deployment.yaml"
export BASE_IMAGE_NAME=${DOCKER_REPO_PATH}/${APPLICATION_NAME}
export DOCKER_IMAGE=${BASE_IMAGE_NAME}:${GIT_COMMIT}
export LATEST_TAG=${BASE_IMAGE_NAME}:latest

echo $APPLICATION_NAME
echo $K8s_DEPLOYMENT_FILE
echo $BASE_IMAGE_NAME
echo $DOCKER_IMAGE
echo $LATEST_TAG

